### ISSUE TITLE
いらない？

### ISSUE THREAD

**Issue by C0A21069** [yu-kod/ProjExD#6]
https://github.com/yu-kod/ProjExD/blob/a904e5df5d9a9822cd091566d4ebcdfd09132974/ex02/calc.py#L8　なくすと勝手にぴったりのサイズにしてくれるからなくてもいいかもしれない

**Comment by yu-kod** [comment]
ボタンのサイズに画面を合わせるというより、画面のサイズにボタンを合わせたいので、本プロジェクトではその行は削除しません
