### ISSUE TITLE
まとめられるかもしれない

### ISSUE THREAD

**Issue by C0A21069** [yu-kod/ProjExD#8]
https://github.com/yu-kod/ProjExD/blob/ddf2495e13b417effd3708ee12ed08c1cabb54df/ex03/maze.py#L31
31から44くらいにかけて同じようなことが書いてあるからまとめられる？

**Comment by yu-kod** [comment]
selfでオブジェクトを指定しているのでうまく動作するか分からないと思っています。
修正にかかるコストが大きそうなので、現段階では修正しません。
